codecov/uploader

.circleci/config.yml
.gitignore
README.md

Using ghr, create a new release with the binaries on GitHub with each merge to master branch.

Add deploy job to pipeline

---

.circleci/config.yml

Make binaries executable prior to packaging.

---

src/helpers/files.js
src/index.js
test/helpers/files.test.js

[CE-2897] Add end of file marker

---

.gitignore
src/ci_providers/provider_circleci.js
src/helpers/web.js
src/index.js
test/helpers/web.test.js

Minor code cleanup changes per DeepCode suggestions.

Implement DeepCode suggestions

---

.circleci/config.yml

This is to match the version we are build Alpine on

ci: upgrade build node to 14.16.1

---

bin/codecov
src/helpers/web.js
src/index.js
test/helpers/web.test.js
test/index.test.js

-N The commit SHA of the parent for which you are uploading coverage.

Parent commit sha -N

---

src/helpers/validate.js
test/helpers/validate.test.js
test/index.test.js

Allow flags with dash
Closes #84

Allow flags with dash

---

package.json
src/helpers/files.js
src/helpers/web.js
test/helpers/files.test.js
test/helpers/validate.test.js
test/index.test.js

Adding encoding to spawnSync to return as a string so it wont throw an error
Should help #85

fix no git repo error

---

npm-shrinkwrap.json
package.json
src/helpers/files.js
src/helpers/logger.js
src/helpers/web.js
src/index.js
test/helpers/logger.test.js
test/helpers/web.test.js
test/index.test.js

Currently , the `-v` vrbose flag does not do anything. Creating a logger wrapper and the tests, then will convert all output to use the logger.

Add verbose logging

---

bin/codecov
src/index.js
test/index.test.js

Feature toggle `-X` param.
Only includes disabling `network` at this time.

Add feature toggle param

---

bin/codecov
src/helpers/files.js
src/helpers/logger.js
src/index.js
test/helpers/files.test.js
test/index.test.js

`-c` clean up coverage reports

Move discovered coverage reports to the trash

---

src/ci_providers/index.js
src/ci_providers/provider_githubactions.js
src/ci_providers/provider_template.js
test/index.test.js
test/providers/index.test.js
test/providers/provider_githubactions.test.js

Adds the GitHub Actions provider

Add base GitHub Actions provider

---

.circleci/config.yml

Update the node binary to node.v16.2.0_b57a0d7c9ecba551879997ac44bba3c9d9443df5

chore(alpine): update node binary to v16

---

src/ci_providers/provider_circleci.js
src/ci_providers/provider_githubactions.js
src/ci_providers/provider_local.js
src/ci_providers/provider_template.js
test/providers/index.test.js
test/providers/provider_circleci.test.js
test/providers/provider_githubactions.test.js

Refactors tests in `index.ts` to check for parameters
Adds tests for CircleCI provider
Removes the `private` function calls from API

test: Add CircleCI tests and refactor testing

---

src/ci_providers/index.js
src/ci_providers/provider_template.js
src/ci_providers/provider_travisci.js
test/providers/index.test.js
test/providers/provider_travisci.test.js

feat: Add Travis provider

---

src/ci_providers/index.js
src/ci_providers/provider_jenkinsci.js
test/helpers/files.test.js
test/providers/index.test.js
test/providers/provider_jenkinsci.test.js
test/providers/provider_local.test.js
test/providers/provider_travisci.test.js

Adds the Jenkins CI provider
Also moves local provider tests to a new file

feat: Add Jenkins CI provider

---

.husky/pre-commit

fix precommit hook

---

src/helpers/web.js

fix: correct headers

---

src/ci_providers/provider_azurepipelines.js
src/ci_providers/provider_template.js
src/helpers/files.js
src/helpers/web.js
src/index.js

Fix: @returns JSDoc annotations for string

---

src/ci_providers/index.js
src/ci_providers/provider_bitbucket.js
test/providers/provider_bitbucket.test.js

feat: New Bitbucket provider

---

bin/codecov
src/helpers/logger.js
src/helpers/web.js
src/index.js
test/index.test.js

Adding upload urls to logging in verbose mode.
Cleaning up some code

verbose and cleanup

---

src/ci_providers/index.js
src/ci_providers/provider_cirrus.js
test/providers/provider_cirrus.test.js

https://cirrus-ci.org/guide/writing-tasks/#environment-variables

Adding Cirrus CI provider

---

bin/codecov
src/helpers/web.js
src/index.js
test/helpers/web.test.js

This will allow for more usage analytics on how the uploader is being used.

feat: Allow for source from wrappers

---

.circleci/config.yml

ci: fix issue with the *-without-git job not having coverage

---

src/helpers/web.js
src/index.js

Correctly validate tokens to prevent invalid ones from reaching the server

Correctly validate tokens to prevent invalid ones from reaching the server

---

.circleci/config.yml
src/helpers/web.js
src/index.js

Hotfix: validateToken not taking in a token

---

src/index.js
test/index.test.js

Adds a log if the token was not specified or if it is empty

fix: Specify log if no token available or empty

---

src/ci_providers/provider_teamcity.js
test/providers/provider_teamcity.test.js

fixes https://github.com/codecov/uploader/issues/219

fix: Add default Teamcity slug

---

src/ci_providers/provider_local.js
test/providers/provider_local.test.js

Fixes https://github.com/codecov/uploader/issues/229

fix: Try to use args before git

---

.circleci/config.yml
bin/codecov
src/ci_providers/provider_azurepipelines.js
src/ci_providers/provider_githubactions.js
src/ci_providers/provider_local.js
src/ci_providers/provider_template.js
src/helpers/files.js
src/helpers/git.js
src/helpers/logger.js
src/helpers/token.js
src/helpers/util.js
src/helpers/web.js
src/index.js
test/helpers/files.test.js
test/helpers/logger.test.js
test/helpers/token.test.js
test/test_helpers.js
tsconfig.json

Create distinct log methods with levels and timestamps
Add some verbose logs and set the stage to easily add more

Better logs

---

npm-shrinkwrap.json
package.json
src/helpers/files.js
src/index.js
test/helpers/files.test.js

This PR makes globbing asynchronous.
- Test runs in the CI are ~1,450% faster
https://app.circleci.com/pipelines/github/codecov/uploader/887/workflows/9076a1ff-104c-49cb-b944-769380335b6e/jobs/6518/parallel-runs/0/steps/0-105
> 1m 49s
https://app.circleci.com/pipelines/github/codecov/uploader/906/workflows/a490529d-ad28-4c3b-9c64-6eb5a707f96f/jobs/6718/parallel-runs/0/steps/0-105
> 7s

Optimize glob functionality

---

src/ci_providers/provider_appveyorci.js
src/ci_providers/provider_azurepipelines.js
src/ci_providers/provider_bitbucket.js
src/ci_providers/provider_buildkite.js
src/ci_providers/provider_circleci.js
src/ci_providers/provider_cirrus.js
src/ci_providers/provider_codebuild.js
src/ci_providers/provider_drone.js
src/ci_providers/provider_githubactions.js
src/ci_providers/provider_gitlabci.js
src/ci_providers/provider_jenkinsci.js
src/ci_providers/provider_local.js
src/ci_providers/provider_teamcity.js
src/ci_providers/provider_template.js
src/ci_providers/provider_travisci.js
src/ci_providers/provider_wercker.js
src/index.js
test/providers/index.test.js

Helps https://github.com/codecov/codecov-action/issues/451

fix: Add verbose env var names

---

.circleci/config.yml
bin/codecov.ts
src/helpers/files.ts
src/index.ts
test/helpers/files.test.ts
test/index.test.ts

fixes https://github.com/codecov/codecov-action/issues/428

Fix support glob files

---

src/helpers/files.ts

Use fast-glob

---

src/ci_providers/provider_appveyorci.ts
src/ci_providers/provider_azurepipelines.ts
src/ci_providers/provider_bitbucket.ts
src/ci_providers/provider_buildkite.ts
src/ci_providers/provider_circleci.ts
src/ci_providers/provider_cirrus.ts
src/ci_providers/provider_codebuild.ts
src/ci_providers/provider_drone.ts
src/ci_providers/provider_githubactions.ts
src/ci_providers/provider_gitlabci.ts
src/ci_providers/provider_jenkinsci.ts
src/ci_providers/provider_local.ts
src/ci_providers/provider_teamcity.ts
src/ci_providers/provider_travisci.ts
src/ci_providers/provider_wercker.ts

Related https://github.com/codecov/uploader/pull/274

fix: Remove export of function _getPR

---

src/helpers/files.ts

fixes https://github.com/codecov/uploader/issues/275

refactor: Remove old isBlacklisted

---

src/ci_providers/provider_travisci.ts
test/providers/provider_travisci.test.ts

fix: correct travis ci detection

---

npm-shrinkwrap.json
package.json
src/helpers/web.ts

fixes https://github.com/codecov/uploader/issues/251

chore: Use snake-case package

---

src/helpers/web.ts
test/helpers/web.test.ts

fix: url parsing from post results

---

src/helpers/web.ts
test/helpers/web.test.ts

Fixes #301 
Linux binary tested [here](https://app.travis-ci.com/github/tagatac/bagoup/builds/236026747) and looks good:
```
[2021-08-23T19:39:44.624Z] ['info'] Pinging Codecov: https://codecov.io/upload/v4?package=uploader-0.1.0&token=*******&branch=codecov-400&build=33.1&build_url=&commit=a3c175b59f8ed4541457c911c36ecd1dc039ea1b&job=533308429&pr=&service=travis&slug=tagatac/bagoup&name=&tag=&flags=&parent=
[2021-08-23T19:39:44.900Z] ['info'] Uploading...
[2021-08-23T19:39:45.067Z] ['info'] {"status":"success","resultURL":"https://codecov.io/github/tagatac/bagoup/commit/a3c175b59f8ed4541457c911c36ecd1dc039ea1b"}
```

Convert NaN PR numbers to the empty string

---

src/ci_providers/provider_bitbucket.ts
test/providers/provider_bitbucket.test.ts

Use `BITBUCKET_REPO_FULL_NAME`

---

src/helpers/web.ts

Use optional chaining to access `text`

---

src/helpers/web.ts
test/helpers/web.test.ts

Encode query strings

---

src/helpers/web.ts
test/helpers/web.test.ts

Revert 363

---

bin/codecov.ts

To aid in troubleshooting https://github.com/codecov/uploader/issues/372 and https://github.com/codecov/codecov-action/issues/509

chore: improve logging on binary exit

---

src/helpers/files.ts
test/helpers/files.test.ts

feat: use `git ls-files`

---

CHANGELOG.md
npm-shrinkwrap.json
package.json
src/ci_providers/provider_herokuci.ts

Release 0.1.10

---

src/index.ts

This PR modifies the sectional comments in index.ts with fold regions. The [Folding](https://code.visualstudio.com/docs/editor/codebasics#_folding) section from the VS Code user guide goes over the feature as it exists in VS Code.

chore: use code regions

---

HELPFILE
src/helpers/cli.ts
src/index.ts
test/index.test.ts

Use the `-X search` from the bash uploader
Closes #514

Add option to NOT search for coverage files

---

src/ci_providers/provider_drone.ts
test/providers/provider_drone.test.ts

See e.g. https://0-8-0.docs.drone.io/environment-reference/

fix: alternative env vars for drone build url

---

src/index.ts

A future PR could
- use the ECMAScript URL class constructor to validate URLs passed by the user
- modify the upload-related functions to accept ECMAScript URL objects in place of their current string parameters
Fixes #452

fix: remove unnecessary validation

---

src/ci_providers/index.ts
src/ci_providers/provider_woodpecker.ts
src/helpers/logger.ts
test/providers/provider_woodpecker.test.ts

feat: add woodpecker provider

---

.circleci/config.yml

- #467 
- #554 
- #555 
- #556 
- #557 
- #561 
- #566 
- #577

Release v0.1.15

---

renovate.json

source: https://web.archive.org/web/20220323140305/https://docs.renovatebot.com/presets-docker/#dockerpindigests

chore(deps): adjust renovate to use pin digests

---

renovate.json

source: https://web.archive.org/web/20220122031855/https://docs.renovatebot.com/modules/manager/circleci/
source: https://web.archive.org/web/20220122031855mp_/https://docs.renovatebot.com/modules/manager/

chore(debs): enabling pinning circleci images

---

renovate.json

source: https://web.archive.org/web/20220328140323/https://docs.renovatebot.com/presets-helpers/#helperspingithubactiondigests

chore(deps): pin github actions digests

---

.circleci/config.yml

source: https://web.archive.org/web/20220328171638/https://discuss.circleci.com/t/legacy-convenience-image-deprecation/41034

chore(ci): update namespace, comments, reorder

---

package.json

Whoops, forgot to bump package.json

fix: bump package.json

---

CHANGELOG.md
npm-shrinkwrap.json
package.json
src/ci_providers/provider_gitlabci.ts
src/helpers/gcov.ts

* chore(release): 0.1.21 by @thomasrockhu-codecov in https://github.com/codecov/uploader/pull/706
* fix: bump package.json by @thomasrockhu-codecov in https://github.com/codecov/uploader/pull/708
* Use CI_MERGE_REQUEST_SOURCE_BRANCH_SHA for GitLab CI by @eliatcodecov in https://github.com/codecov/uploader/pull/710
* @eliatcodecov made their first contribution in https://github.com/codecov/uploader/pull/710
**Full Changelog**: https://github.com/codecov/uploader/compare/v0.1.21...v0.1.22

Release 0.1.22

---

src/helpers/cli.ts
src/helpers/coveragepy.ts
src/index.ts
src/types.ts
test/helpers/coveragepy.test.ts

Adds `coveragepy` support, it automagic runs `coverage xml`

feat: add coveragepy xml support

---

npm-shrinkwrap.json
package.json

chore: remove `nock`

---

npm-shrinkwrap.json
package.json

chore: remove `https-proxy-agent`

---

npm-shrinkwrap.json
package.json

chore: remove `line-reader`

---

CHANGELOG.md
npm-shrinkwrap.json
package.json

* chore(release): 0.2.4 by @drazisil-codecov in https://github.com/codecov/uploader/pull/799
* fix: parse both versions of ssh urls for remotes by @vihangm in https://github.com/codecov/uploader/pull/793
* fix(deps): update dependency undici to v5.5.1 by @renovate in https://github.com/codecov/uploader/pull/804
* Fix typo: mannually -> manually by @dmivankov in https://github.com/codecov/uploader/pull/805
* Handle strings like before by @mitchell-codecov in https://github.com/codecov/uploader/pull/808
* fix(deps): pin dependency undici to 5.5.1 by @renovate in https://github.com/codecov/uploader/pull/806
* chore(deps): update node.js to v17.9.1 by @renovate in https://github.com/codecov/uploader/pull/795
* chore(deps): update dependency google/cloud-sdk to v390 by @renovate in …

chore(release): 0.2.5

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

_(just noticed that these contain some stub values)_

chore(gh): use real labels in issue templates

---

src/helpers/web.ts

fixes https://github.com/codecov/uploader/issues/881

fix: force using ipv4 for dns lookup

---

src/helpers/files.ts
test/helpers/files.test.ts

feat: support cobertura reports generated by Microsoft.CodeCoverage

---

src/helpers/cli.ts
src/helpers/swift.ts
src/index.ts
src/types.ts
test/helpers/swift.test.ts

Fixes https://github.com/codecov/uploader/issues/803
Based off of [codecov-bash](https://github.com/codecov/codecov-bash/blob/master/codecov#L219-L239)

fix: add swift coverage conversions

---

.circleci/config.yml

Do not upload test reports to Codecov 
Fixes #1091

Do not upload test reports to Codecov 

---

src/helpers/web.ts
test/index.test.ts

Fixes: https://github.com/codecov/engineering-team/issues/552

chore: make status say processing instead of success

---

src/helpers/web.ts

Retry on errors as referenced in https://github.com/nodejs/undici/blob/70caae82a3ba63c572dfd3e90676cd9209ae70e0/docs/api/Errors.md

chore(error): add undici error code to retry logic
