codecov/uploader

src/helpers/web.js
Changes to codecov's uploading infrastructure mean the public-read header is no longer required.
=> Remove public read header

renovate.json
pkg 4.5.x will not correctly build node static on alpine.
https://github.com/codecov/uploader/issues/72 opened to investigate. Pinning for now.
=> chore: pin version of pkg for renovate

bin/codecov, package.json, src/helpers/web.js, src/index.js, test/index.test.js, test/test_helpers.js
Adding name flag as defined in the upload API https://docs.codecov.io/reference#upload
Removed `expect` as it is not needed as jest has it built in.
Added JSDoc comments to some functions.
Adding coverage to index.js file
=> Custom defined name of the upload

.circleci/config.yml
Upgrade the version of Node that Linux and OSX are built in to 12.16.1, to match the alpine version.
=> ci: upgrade node build version to 12.16.1

bin/codecov, src/index.js, test/fixtures/coverage.txt, test/fixtures/other/coverage.txt, test/index.test.js
-s flag to load files from a specified coverage directory instead of from project root.
=> Coverage directory -s

.circleci/config.yml
This should drastically cut down the build time since we are using the prebuilt binary from https://github.com/codecov/node-static-alpine/releases/tag/node.v14.16.1_0b668b007c0533fa4be1b24c66941a06f5965fdf instead of building node on each run.
=> ci: build node on alpine using prebuilt binary

.circleci/config.yml
closes #99 
This compares the SHASUM hashes on the pre-build node binary prior to it's use.
=> ci: download and compare hashes for node binary

.circleci/config.yml
We should deploy only on the `release` branch. The PRs to this branch should list a changelog, as I believe that will be the content of the release on GitHub.
=> ci: change pipeline to deploy on release branch

.circleci/config.yml, src/ci_providers/provider_githubactions.js, test/providers/provider_githubactions.test.js
chore(deps): update google/cloud-sdk docker tag to v344 (#127) …
chore: Causes the correct server URL to be set in GitHub Actions. (#131) …
=> Update to Cloud SDK and GitHub Actions support

src/helpers/web.js
We now want to send token as a header vs. URL param for security purposes.  Same as was done in https://github.com/codecov/codecov-bash/pull/439
=> chore: send upload token as header vs. url param

src/helpers/files.js, test/dummy.codecov.exe, test/helpers/files.test.js
This fixes an issue where codecov.exe would attempt to upload itself on Windows, and the report processing would fail due to it being a binary.
=> test: exclude codecov.exe on windows

.circleci/config.yml, src/ci_providers/provider_githubactions.js, src/helpers/files.js, src/helpers/web.js, test/dummy.codecov.exe, test/helpers/files.test.js, test/providers/provider_githubactions.test.js
* chore(deps): update google/cloud-sdk docker tag to v344 (#127) …
* chore: Send upload token as header vs. URL param (#132) ...
* fix: Causes the correct server URL to be set in GitHub Actions. (#131) …
* fix: exclude codecov.exe on windows (#134) …
=> Correct Windows uploads and enable GitHub Actions support on GHE

.circleci/config.yml, src/helpers/files.js
This changes `path` to use `path.posix` per https://nodejs.org/dist/latest-v14.x/docs/api/path.html#path_windows_vs_posix
Thanks @eddiemoore !
This also runs tests on Windows prior to building.
=> fix: use posix path

.circleci/config.yml, src/helpers/validate.js, test/helpers/validate.test.js
=> fix: correct flags regex to match server and docs

bin/codecov, src/index.js
This makes the main() method testable.
=> refactor: all exits moved to cli, throw as needed

.circleci/config.yml, README.md, bin/codecov, npm-shrinkwrap.json, package.json, src/helpers/validate.js, src/helpers/web.js, src/index.js, test/helpers/validate.test.js
* fix: correct flag name regex
* remove `x-` from some headers
* refactor exit logic for improved testing
* update several dependencies
=> fix: correct flag name regex, remove `x-` from some headers

.circleci/config.yml
CircleCI is depreciating xcode 10
https://discuss.circleci.com/t/xcode-deprecation-notice-9-4-1-10-0-0-10-1-0-and-10-2-1/40515
Upgrading to latest stable per https://circleci.com/docs/2.0/testing-ios/
=> ci: update to xcode 12

src/ci_providers/provider_azurepipelines.js, src/ci_providers/provider_githubactions.js, src/helpers/git.js, src/helpers/validate.js, test/providers/provider_azurepipelines.test.js, test/providers/provider_githubactions.test.js, test/providers/provider_gitlabci.test.js, test/test_helpers.js
* refactor: change exec Sync to use spawnSync. I believe this was part of the fix for Command Injection on codecov-node, can't confirm. @eddiemoore and @RA80533, would love your review.
* test: add test and alert for execSync use to test/test_helpers.js
=> refactor: update to use spawnsync

src/helpers/files.js
This should allow php projects to have reasonable performance when using the uploader.
=> Add vendor dir to file blacklist

src/index.js, test/index.test.js
If multiple files are supplied to the uploader, it currently pushes all of them as the first element of an array e.g.
```
[
[ first_file, second_file ]
]
```
This breaks the uploader's ability to read the files.
=> fix: Allow multiple files to be read

src/index.js
`process.env.CODECOV_TOKEN` can be `undefined` which will bork this call. It should be taking from `token` set earlier
=> hotfix: validateToken needs to take in the token

npm-shrinkwrap.json, package.json, src/helpers/files.js, src/helpers/token.js, src/index.js, test/fixtures/yaml/.codecov.yml, test/fixtures/yaml/codecov.yaml, test/fixtures/yaml/codecov.yml, test/helpers/token.test.js
fixes https://github.com/codecov/codecov-action/issues/430
related https://github.com/codecov/uploader/issues/222
related https://github.com/codecov/uploader/issues/219
related https://github.com/codecov/uploader/issues/217
=> feat: Allow for token from yaml

src/helpers/validate.js, test/helpers/validate.test.js, test/index.test.js
fixes https://github.com/codecov/codecov-action/issues/436
=> fix: Validate UUID tokens

src/helpers/files.js, src/helpers/logger.js, src/index.js, test/helpers/logger.test.js
Instances of `@ts-check` override any project configuration of files containing the compiler directive. In other words, the compiler options derived from the root tsconfig.json file do not take effect in their entirety for any scripts that contain the `@ts-check` directive. A side effect of this interaction is that type definitions available through user-installed packages are not accessible in any scripts containing the compiler directive.
Fixes #248
=> Remove extraneous `@ts-check` directives

src/helpers/files.ts
I'll be honest, not totally sure how we are doing `manualBlacklist` and `globBlacklist` anymore. 
fixes https://github.com/codecov/uploader/issues/259
=> fix: Remove __pycache__ and .tox folders from search

tsconfig.json
TypeScript is unable to perform back-to-back compilations due to the input directory being intertwined with the would-be output directory:
```console
$ tsc  --build
error TS5055: Cannot write file '/[…]/uploader/dist/bin/codecov.d.ts' because it would overwrite input file.
[…]
```
=> Add "dist/*" to `exclude`

src/helpers/files.ts
Salesforce has added new json files `test-result-<testrunid>-codecoverage.json` that contain class/method coverage info on a per test basis. We only need the existing `test-result-codecoverage.json` file to calculate per line coverage, so we can safely ignore the other ones.
=> Add new Apex file format to upload ignore list

src/helpers/web.ts
Coverage reports are currently sent twice:
- [`uploadToCodecov`](https://github.com/codecov/uploader/blob/037e1e74331080fdad25e550d8fdb7785c17b330/src/helpers/web.ts#L94)
- [`uploadToCodecovPUT`](https://github.com/codecov/uploader/blob/037e1e74331080fdad25e550d8fdb7785c17b330/src/helpers/web.ts#L59)
=> Don't upload coverage reports more than once

src/index.ts
The current filename validation is too strict; furthermore, it is not currently necessary since the underlying file system is capable of raising an error if it receives an invalid file name.
Fixes #303
=> Remove filename validation

bin/codecov.ts, src/helpers/web.ts, test/helpers/web.test.ts
Flags are now getting passed in as a `string`, not a `string[]`, so the prior validation would throw out the entire string.
=> fix: Parse multiple flags properly

src/helpers/files.ts
Do not upload or consider the SHA files as coverage files
=> fix: prevent SHA files from being uploaded

src/helpers/files.ts, test/helpers/files.test.ts
=> fix: 🐛 Preserve LF in the report file names list

src/ci_providers/provider_herokuci.ts
This PR fixes an error where Jenkins is incorrectly detected as Heroku, thus breaking the upload of coverage data since the provider cannot find the proper SHA for the report.
The problem is that the environment variable `HEROKU_TEST_RUN_BRANCH` is `undefined` which when losely compared to empty string will become `true` whereas what we really want to know is if it actually has any value. Looked through the other providers and you seem to like checking this by casting it as a boolean so I decided to do the same
=> Fix false positive detection for Heroku-provider

src/ci_providers/provider_githubactions.ts, src/helpers/files.ts, src/helpers/git.ts, test/helpers/files.test.ts
Note: the specified encoding should be redundant since we call toString on the buffer response in `runExternalProgram`
https://github.com/codecov/uploader/blob/722c8191c20cda5fba026f889069ed40ef8da4e6/src/helpers/util.ts#L15
=> chore: swap spawnSync calls for helper function runExternalProgram

src/helpers/files.ts, test/fixtures/codecov.ps1, test/fixtures/codecov.sh, test/fixtures/other/codecov.ps1, test/fixtures/other/codecov.sh, test/helpers/files.test.ts
- Add tests to check that scripts and config files are removed from coverage files by default: I expect this to fail, see #529
- Add the missing subdir globstar
=> Fix: Don't collect scripts as coverage files

.circleci/config.yml
do not replace published github release if tag exists
=> ci: do not allow overwrite

.circleci/config.yml, vendor/README.md
after discovering that github releases may not be immutable,
we are vendoring the ghr binary
=> ci: vendor ghr

bin/codecov.ts, src/ci_providers/provider_githubactions.ts, src/helpers/files.ts, src/helpers/logger.ts, src/helpers/provider.ts, src/helpers/token.ts, src/index.ts, test/helpers/logger.test.ts
All operations that should depend on the set logging level must go through UploadLogger. The free functions are still required e.g. for things like `verbose(`Start of uploader: ${start}...`, realArgs.verbose)` running outside of `main`, so I kept them.
Consistently using `UploadLogger.verbose` is IMO more readable and makes it clear, that logging levels are used. If the free functions are to be preferred, the class can be removed.
To avoid mistakes with the free `verbose` remove the default Argument as that doesn't make sense anyway and is the source of current bugs. Those are fixed by this change as they all go through `UploadLogger` now.
@drazisil-codecov This is basically the all-round fix for https://github.com/codecov/uploader/pull/533#issuecomment-1002999737
The issue was likely …
=> fix: use logging class for most verbose calls

src/helpers/files.ts, test/helpers/files.test.ts
`contains` was inadvertently passed as an option to micromatch in [`filterFilesAgainstBlockList`]:
https://github.com/codecov/uploader/blob/7a9a54e245e629c9a1c8891352cf6941ae4d2496/src/helpers/files.ts#L339-L341
https://github.com/codecov/uploader/pull/577#discussion_r787846281
Tests now specifically cover the following files:
- coverage.info[^1]
- coverage.opencover.xml[^2]
- gap-coverage.json[^3]
[`filterFilesAgainstBlockList`]: https://github.com/codecov/uploader/blob/7a9a54e245e629c9a1c8891352cf6941ae4d2496/src/helpers/files.ts#L339-L341
[^1]: https://github.com/codecov/uploader/issues/614#issuecomment-1030237895
[^2]: https://github.com/codecov/uploader/issues/614#issuecomment-1030371776
[^3]: https://github.com/codecov/uploader/issues/614#issuecomment-1030662555
=> fix: include coverage files

.circleci/config.yml
As recommended  by https://web.archive.org/web/20220216131451/https://circleci.com/docs/2.0/images/linux-vm/14.04-to-20.04-migration/
> If you have specified an Ubuntu 14.04-based image or you are using machine: true in your config file, please see our [migration guide](https://circleci.com/docs/2.0/images/linux-vm/14.04-to-20.04-migration/) to upgrade to a newer version of Ubuntu image in order to avoid any service disruption during the brownout & subsequent EOL.
=> chore: update machine image

src/ci_providers/provider_azurepipelines.ts, src/ci_providers/provider_githubactions.ts, test/providers/provider_azurepipelines.test.ts, test/providers/provider_githubactions.test.ts
The double quotes get escaped by execFileSync and then are part of the output which makes the Regex fail to match.
Remove them to avoid this.
See https://github.com/boostorg/boost-ci/runs/5394406101?check_suite_focus=true:
```
['verbose'] Handling PR with parent hash(es) '"86f4b7cb20e29080b366ee1593c1135038bda4bf cd099c05fc6d88115e9bbdc0c60b23fb5a0fa952"' of current commit.
['info']     Commit with SHA 9e556cae25da2cb0438a10e81d3f78ddcc7e8510 of PR 125 is not a merge commit
```
Can be reproduced in a shell by running `git show --no-patch --format=\"%P\"`
@drazisil-codecov Finally found this!
=> Fix detection of merge commits on Github Actions an AzP

CHANGELOG.md, npm-shrinkwrap.json, package.json
- add helper arg array method, pass in extra gcov args ([57459e3](https://github.com/codecov/uploader/commit/57459e3b98ea9855da67f7d3c9ac6cd2a8e1c398))
=> Release 0.1.19

src/helpers/gcov.ts
Before this change files like
```
test/.gcovfiles/gcov.gnco
```
would be ignored
=> fix: include directories and files that start with . with gcov

src/ci_providers/provider_gitlabci.ts
Lets CI_MERGE_REQUEST_SOURCE_BRANCH_SHA take precedence over CI_COMMIT_SHA. This is necessary for more advanced gitlab CI builds that use merge result pipelines. 
Docs: https://docs.gitlab.com/ee/ci/variables/predefined_variables.html
=> Use CI_MERGE_REQUEST_SOURCE_BRANCH_SHA for GitLab CI

CHANGELOG.md, npm-shrinkwrap.json, package.json
* chore(release): 0.1.21 by @thomasrockhu-codecov in https://github.com/codecov/uploader/pull/706
* fix: bump package.json by @thomasrockhu-codecov in https://github.com/codecov/uploader/pull/708
* Use CI_MERGE_REQUEST_SOURCE_BRANCH_SHA for GitLab CI by @eliatcodecov in https://github.com/codecov/uploader/pull/710
* @eliatcodecov made their first contribution in https://github.com/codecov/uploader/pull/710
**Full Changelog**: https://github.com/codecov/uploader/compare/v0.1.21...v0.1.22
=> Release 0.1.22

src/helpers/token.ts, src/helpers/util.ts, test/helpers/files.test.ts, test/helpers/gcov.test.ts, test/helpers/token.test.ts, test/helpers/util.test.ts, test/providers/provider_azurepipelines.test.ts, test/providers/provider_bitbucket.test.ts, test/providers/provider_bitrise.test.ts, test/providers/provider_githubactions.test.ts, test/providers/provider_gitlabci.test.ts, test/providers/provider_herokuci.test.ts, test/providers/provider_jenkinsci.test.ts, test/providers/provider_local.test.ts, test/providers/provider_teamcity.test.ts
Fixes the issue [here](https://github.com/RemedyIT/taox11/runs/5996166946?check_suite_focus=true) where running `gcov` exceeds the buffer size. Also removes unused argument from `token.ts`
=> fix: increase spawnsync buffer

CHANGELOG.md, npm-shrinkwrap.json, package.json
Please note the minor version bump here. I think this is necessary given the new features (`xcode` and `coveragepy`)
* add coveragepy xml support ([8353edb](https://github.com/codecov/uploader/commit/8353edbd82e9dd2b9eea607beaa701f3ecef9300))
* add xcode support ([c5e1c70](https://github.com/codecov/uploader/commit/c5e1c70051523d6bb015cbd2e337a4f1df58ef60))
* add more readable number ([d15ccef](https://github.com/codecov/uploader/commit/d15ccef55d84094abfc986bac7b3b53b1263acae))
* add tests for coveragepy ([de90c56](https://github.com/codecov/uploader/commit/de90c56614de8eea5d46aee25f106598cccd534d))
* automagic xml ([626b76b](https://github.com/codecov/uploader/commit/626b76b76caa03ddfc6adf9310d3a22ac04619c4))
* bump package.json …
=> Release 0.2.0

src/index.ts
Workaround for #745. Instead of keeping the contents into a `string`, keep them into a `Buffer` instead. All the APIs seemed to already accept buffers.
`Buffer.from()` does [copy the underlying data](https://nodejs.org/api/buffer.html#bufferfrom-bufferalloc-and-bufferallocunsafe), but that should be ok since the strings we are copying are short lived
`npm run test` passes
following the repro steps on #745:
**before**:
```
[2022-04-30T23:08:35.567Z] ['info'] Processing /Users/gabriel.russo/uploader/giant_files/4.dat...
[2022-04-30T23:08:35.660Z] ['info'] Processing /Users/gabriel.russo/uploader/giant_files/5.dat...
[2022-04-30T23:08:35.748Z] ['info'] Processing /Users/gabriel.russo/uploader/giant_files/6.dat...
[2022-04-30T23:08:35.838Z] ['error'] There was an error running the uploader: …
```
=> fix: store upload file contents on a Buffer

CHANGELOG.md, npm-shrinkwrap.json, package.json
* **deps:** update dependency https-proxy-agent to v5.0.1 ([90a68c0](https://github.com/codecov/uploader/commit/90a68c021b0cc7f098fb644934b1d29771e4fd88))
* **deps:** update dependency yargs to v17.4.1 ([d0d9548](https://github.com/codecov/uploader/commit/d0d95483cc1aa5a7da86969af3f42d7824d280ef))
* increase maxBuffer of spawnSync ([c121446](https://github.com/codecov/uploader/commit/c12144697e95051b061488feae60db4b98d600c2))
* store upload file contents on a Buffer ([0209be2](https://github.com/codecov/uploader/commit/0209be276dc9df75b41da8436f5d7209ae368a11))
* fix coveragepy autorun [0773002](https://github.com/codecov/uploader/commit/0773002388faad66cf155ef36d968d718c03cd87)
**Full Changelog**: https://github.com/codecov/uploader/compare/v0.2.0...v0.2.1
=> chore(release): 0.2.1

CHANGELOG.md, npm-shrinkwrap.json, package.json
v0.2.1 may have been corrupted
**Full Changelog**: https://github.com/codecov/uploader/compare/v0.2.0...v0.2.2
=> chore(release): 0.2.2

CHANGELOG.md, npm-shrinkwrap.json, package.json
v0.2.1 may have been corrupted
**Full Changelog**: https://github.com/codecov/uploader/compare/v0.2.0...v0.2.2
=> chore(release): 0.2.2 (#754)

src/ci_providers/provider_jenkinsci.ts
When using multibranch pipelines, Jenkins will create a new branch for pull requests named "PR-X" where X is the ID. This means that submitting the branch name to Codecov will not represent real branches from the project.
It is also the case that in multibranch projects, Jenkins may merge `master` into the working branch. In the event this creates a merge commit the `GIT_COMMIT` envvar will point to this rather than the commit being tested (and thus the given commit hash will be irrelevant when posting to external services). This PR does not fix that but adds a note in the code to assist future people encountering this issue.
=> Jenkins: branch/commit handling for multibranch pipelines

CHANGELOG.md, npm-shrinkwrap.json, package.json
* **deps:** update dependency https-proxy-agent to v5.0.1 ([90a68c0](https://github.com/codecov/uploader/commit/90a68c021b0cc7f098fb644934b1d29771e4fd88))
* **deps:** update dependency undici to v5.2.0 ([e7fb541](https://github.com/codecov/uploader/commit/e7fb54164013773066c144140344dcd5f88b0eba))
* **deps:** update dependency yargs to v17.4.1 ([d0d9548](https://github.com/codecov/uploader/commit/d0d95483cc1aa5a7da86969af3f42d7824d280ef))
* **deps:** update dependency yargs to v17.5.0 ([5911bb5](https://github.com/codecov/uploader/commit/5911bb541a0474cbeb6ad01b095f154a0ea0b7dd))
* increase maxBuffer of spawnSync ([c121446](https://github.com/codecov/uploader/commit/c12144697e95051b061488feae60db4b98d600c2))
* store upload file contents on a Buffer …
=> chore(release): 0.2.3

src/helpers/git.ts, test/helpers/git.test.ts
Fixes #792
Signed-off-by: Vihang Mehta <vihang@pixielabs.ai>
=> fix: parse both versions of ssh urls for remotes

.gitignore
This PR updates the ignore rules for output directories to, rather than ignore the files within them _specifically_ by rule, ignore the output directories themselves. This has the benefit of providing a better IDE experience wherein the folder (rather than just the contents _within_ the folder) will appear ignored.
=> chore: ignore output directories

src/helpers/checkSlug.ts, src/index.ts, test/helpers/checkSlug.test.ts
If slug is missing a forward slash, or "undefined", log error and exit
=> refactor: exit on invalid slug

src/helpers/files.ts
If a directory or file exists, but Codecov does not have read access, `glob` will return a 
```
There was an error running the uploader: EACCES: permission denied, scandir <directory>
```
error. This should be avoided, and uploading should continue as expected
Related: https://community.codecov.com/t/cant-make-ignore-option-work-for-directory-with-strict-permissions/3814
=> fix: suppress errors during glob for files

CHANGELOG.md
* accept comma-separated files in args ([#861](https://github.com/codecov/uploader/issues/861)) ([2a3e897](https://github.com/codecov/uploader/commit/2a3e897ba654eea43005e27768435f83ce074d92))
* add gcov executable ([#794](https://github.com/codecov/uploader/issues/794)) ([fecf6b4](https://github.com/codecov/uploader/commit/fecf6b401ea44dcb14f52820107f23170c21709a))
* ignore files ending in .*js ([#798](https://github.com/codecov/uploader/issues/798)) ([1cd0d23](https://github.com/codecov/uploader/commit/1cd0d23322988a9af7f06d7fd8681ce4e5558b5c))
* **deps:** pin dependency undici to 5.5.1 ([#806](https://github.com/codecov/uploader/issues/806)) ([894b823](https://github.com/codecov/uploader/commit/894b8233d0b92694d5f21df8145b908ffb180524))
* **deps:** update dependency https-proxy-agent …
=> chore(release): 0.2.6

CHANGELOG.md, npm-shrinkwrap.json, package.json
* chore(release): 0.3.4 by @thomasrockhu-codecov in https://github.com/codecov/uploader/pull/934
* fix(files): exclude .go and .marker files by @drazisil-codecov in https://github.com/codecov/uploader/pull/935
**Full Changelog**: https://github.com/codecov/uploader/compare/v0.3.4...v0.3.5
=> chore(release): 0.3.5

README.md, src/helpers/files.ts, test/helpers/files.test.ts
This PR updates the `fetchGitRoot` function in `files.ts` to not error when attempting to `runExternalProgram`. Explicitly, this change involves: 
1. Updating the return statement to return the `currentWorkingDirectory` if `gitRoot == ""` 
2. Updating the `catch (error)` block to log the error, and then returning the `currentWorkingDirectory` instead of `throw new Error`. 
3. Updating the associated test for `fetchGitRoot()` inside of `files.tests.ts`
=> Update fetchGitRoot to not halt execution

.circleci/config.yml, Makefile, package.json
fixes https://github.com/codecov/uploader/issues/523
=> chore(arch): build aarch64

src/helpers/files.ts, test/helpers/files.test.ts
Fixes: https://github.com/codecov/uploader/issues/544
=> fix: handle windows drive letter at start of path

src/helpers/web.ts, test/helpers/web.test.ts
fixes https://github.com/codecov/uploader/issues/1180
=> fix: add ETIMEDOUT

src/helpers/web.ts, test/helpers/web.test.ts
add `User-Agent: codecov-uploader/{version}` header to outgoing requests to the codecov api so we can track API usage compared to gazebo and `codecov-cli` or by uploader version
it appears we send a `package` param to a legacy upload endpoint with this information already which can tell us what proportion of that endpoint's traffic is from this uploader, but setting a user agent across the board tells us for all endpoints, or what proportion of overall API traffic is from this uploader
=> feat: add user agent to requests to the codecov api

HELPFILE, src/helpers/cli.ts, src/helpers/files.ts, src/helpers/web.ts, src/index.ts, src/types.ts, test/helpers/coveragepy.test.ts, test/helpers/files.test.ts, test/helpers/token.test.ts
This option is being added to allow users to manually decide to use the current working directory instead of the git root when fetching the git root automatically.
=> feat: add useCWD option to args

.github/workflows/test-and-deploy.yml, npm-shrinkwrap.json, package.json
Adds most of the `test-` jobs with the exception of `aarch64`. Also adds the `release job`
=> chore(ci): add test-alpine job
